name: XSLT Transformation
on: [push]
jobs:
  xslt-transform:
    runs-on: ubuntu-latest
    steps:
     uses: actions/checkout@v4
    - name: XSLT Transformation
      uses: pl-strflt/saxon@v1
      env:
        INPUT_INPUT: junit.xml
      with:
        args: -s:$INPUT_INPUT -xsl:/etc/junit-frames-saxon.xsl output.dir=/github/workspace/$INPUT_OUTPUT
    
